# Generated by Django 3.0.6 on 2020-06-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notki', '0002_wpis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nalezace', to='notki.Category'),
        ),
    ]
